import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const MovieItem = ({list}) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>
					Filmes em Destaque
				</h1>

				<Link href="/busca">Ir para a Busca</Link>


					<ul>
						{list.map(item => (
							<li>
								<a href={`/movie/${item.id}`}>
								<img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width="150"/>
								{item.title}
								</a>
							</li>
						))}
					</ul>


			</main>
		</div>
	)
}

export default MovieItem

export async function getServerSideProps(){
	const res = await fetch('http://localhost:3000/api/trending ');
	const json = await res.json();
	return{
		props:{
			list: json.list
		}
	}
}