import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home = (props) => {
	const {cidade, estado} = props.Localizacao
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>
					Filmes em Destaque
				</h1>
				<h1 className={styles.title}>
					Meu nome é: {props.name} <br />
					Tenho idade: {props.idade} <br />
					Moro em: {cidade} <br />
					Estado: {estado} <br />
				</h1>

			</main>
		</div>
	)
}

export default Home

export async function getServerSideProps(){
	const res = await fetch('https://localhost:3000/api/hello')
	const json = await res.json()
	return{
		props:{
			name:json.name
		}
	}
}