/* eslint-disable linebreak-style */
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable react/prop-types */
/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head';
// import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home = ({ list }) => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <h1 className={styles.title}>
        Filmes em Destaque
      </h1>
      <h1>
        Assista em destaque TOP 1:
        {' '}
        {list[0].title}
      </h1>

      <Link href="/busca">Ir para a Busca</Link>

      <ul>
        {list.map((item) => (
          <li>
            <a href={`/movie/${item.id}`}>
              <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width="150" />
              {item.title}
            </a>
          </li>
        ))}
      </ul>

      <Link href="/sobre">Sobre mim</Link>
    </main>
  </div>
);
export default Home;

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/trending ');
  const json = await res.json();
  return {
    props: {
      list: json.list,
    },
  };
}
